# Generated by Django 5.0.7 on 2024-07-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_remove_sensor_measurments_measurement_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor'),
        ),
    ]
